[package]
name = "ffi_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "ffi_lib"
path = "src/lib.rs"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
